version: "3"
services:
  db:
    image: mongo:4.2-rc
    ports:
      - 27018:27017
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=slabchat
    restart: unless-stopped
  web:
    build:
      context: .
      args:
        # The backend url, needs to be accessible from the frontend
        API_URI: "http://localhost:8080"
    ports:
      - "3000:80"
    environment: {}
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      # The MongoDB address
      DB_URI: "mongodb://root:root@db:27017/slabchat?authSource=admin"
      # A secret token used for authentication
      JWT_SECRET: "1234"
volumes:
  mongodata:
