version: "3"
services:
  db:
    image: mongo:4.2-rc
    env_file: .env.production
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=slabchat
    restart: unless-stopped
  web:
    build: .
    env_file: .env.production
    ports:
      - "3000:80"
  backend:
    build: ./backend
    env_file: .env.production
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
